### ISSUE TITLE
容器検査期限について

### ISSUE THREAD

**Issue by jb7th** [jb7th/suite01#10]
容器検査期限については、それを情報として入力することでどんなメリットがあるのか不透明な部分が多すぎるため、現時点（v0.9.2）では対応していない。
項目の数に比例してシステムは複雑化し、コストが増えていくわけであるから、導入には慎重な議論が必要であろう。

# 分かっていること
1. 購入容器は使い捨てるのが普通であるため、検査期限は問題にならない。
1. レンタル容器の検査期限を気にするユーザーは確かに存在する。だからといって、それをPC上でわざわざ入力し眺めて見たところで、誰得なのかがよくわからない。

**Comment by uniho** [comment]
「分かっていること」の１は

容器検査期限項目は、購入容器で特に重要な項目となるとも考えられるところであるが、現実的には購入容器は使い捨てで使うことが多いので優先順位は低いとのこと。

に修正します。
いずれにせよ、極少数者しか使わない機能の取り込みには慎重な議論が必要です。声のでかいユーザーのいいなりになるだけだったばかりに崩壊したシステムはいくつも見てますし。

**Comment by jb7th** [comment]
# 論点
1. 誰が容器１つ１つの検査期限を入力するのか。
1. 検査期限間近容器一覧のような集計ができるようになるとして、どれほどのニーズが有るのか。
1. 総合的に、ユーザーにとって便利な機能といえるのか。

**Comment by jb7th** [comment]
# 2018/10/16時点での結論
#9 と同じ結論です。
