### ISSUE TITLE
容器所有権について

### ISSUE THREAD

**Issue by jb7th** [jb7th/suite01#9]
容器所有権については、それを情報として入力することでどんなメリットがあるのか不透明な部分が多すぎるため、現時点（v0.9.2）では対応していない。
項目の数に比例してシステムは複雑化し、コストが増えていくわけであるから、導入には慎重な議論が必要であろう。

**Comment by uniho** [comment]
１段落目は次のように修正します。

容器所有権は、容器検査期限項目(#10)と関連する項目であるが、それらを情報として入力することでどんなメリットがあるのか不透明な部分が多すぎるため、現時点（v0.9.2）では対応していない。

ちなみに、これらはあくまでユーザー目線での話です。ディーラー側がこれらの情報に興味があるのは十分わかっていますが、ユーザー側はほとんど興味を持たない情報であるということです。

**Comment by jb7th** [comment]
# 論点
1.  誰がひとつひとつの容器について、容器所有権の情報を入力するのか。
1. 自己所有容器一覧みたいな集計ができたとして、それがなんの役に立つのか。
1. 容器検査期限項目(#10)とセットならそもそも独立の項目としては不要ではないか（検査期限がセットされている＝自己容器となるので）。
1. 総合的に、ユーザーにとって便利な機能といえるのか。

**Comment by jb7th** [comment]
# 2018/10/16時点での結論
容器固有の情報として重要な情報であることは確かではあるが、ユーザーがその情報を活用することで何ができるのかは不明確である。
おそらく、ユーザーに所有権があるとはいっても、プロであるディーラやメーカを無視してユーザーだけで容器を好き勝手に利用できるわけではないため、ユーザー独自の情報としてはほとんど意味がないからであろう。つまり、あなたの容器なんだからプロの助けを借りずに管理せよというのには無理があるということである。

**Comment by jb7th** [comment]
# 2018/10/24時点での結論
在庫容器テーブルにおいては不要な項目であるのは間違いない。
これらの項目が必要になるのは、自己所有容器テーブル（#27）においてである。
